server:
  http_listen_port: 9080

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: 'fastapi-logs'
    static_configs:
      - targets:
          - localhost
        labels:
          job: 'fastapi'
          __path__: /var/log/fastapi/service1/*.log
      - targets:
          - localhost
        labels:
          job: 'fastapi'
          __path__: /var/log/fastapi/service2/*.log